Django_MiniProject_2-master/BLOG_POSTS/urls.py
from django.contrib import admin
from django.urls import path
from BLOG_POSTS import views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import *
urlpatterns = [

        path('register/',views.create,name="register"),
        path('success/',views.success,name="success"),
        path('home/',views.home,name="home"),
        path('create_blog/',views.create_blog,name='create_blog'),
        path('show/',views.show,name='show'),
        path('delete/<int:id>',views.destroy),
        path('edit/<int:id>',views.edit,name='edit'),
        path('update/<int:id>', views.update,name='update')

    ]


if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Django_MiniProject_2-master/CRUDAPP/urls.py
from django.contrib import admin
from django.urls import path
from BLOG_POSTS import views
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('BLOG_POSTS/',include('BLOG_POSTS.urls')),
    path('update/<int:id>', views.update),
    path('',views.homepageview.as_view(),name='home'),
    path('users/',include('users.urls')),
    #path('users/',include('django.contrib.auth.urls'))
    path('accounts/',include("allauth.urls")),
    path('test/',views.test),


]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Django_MiniProject_2-master/users/urls.py
from django.urls import path,include
from .views import SignupView
from users import views

urlpatterns=[
    path("signup/" ,SignupView.as_view(),name="signup"),
]

Django_MiniProject_2-master/BLOG_POSTS/models.py
from django.db import models
import datetime

# Create your models here.
class login(models.Model):
    Name=models.CharField(max_length=30)
    Password = models.CharField(max_length=20)
    ReEnterPassword=models.CharField(max_length=20)
    Email = models.EmailField(max_length=30)

    def __str__(self):
        return self.Name

# Create your models here.

class createblog(models.Model):
    Author_Name = models.CharField(max_length=30)
    places=models.CharField(max_length=30)
    date = models.DateField()
    content_blog=models.CharField(max_length=1000)
    picture=models.ImageField(upload_to='images/')

Django_MiniProject_2-master/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    pass

Django_MiniProject_2-master/BLOG_POSTS/forms.py
from django import forms
from django.core import validators
from django.forms import ModelForm
from.models import login

class loginform(forms.ModelForm):
    class Meta:
        model = login
        fields = '__all__'
        widgets={
        'Password': forms.PasswordInput(),
        'ReEnterPassword':forms.PasswordInput(),

        }

    def clean(self):
        super(loginform, self).clean()
        Name = self.cleaned_data.get('Name')
        Password=self.cleaned_data.get("Password")
        ReEnterPassword=self.cleaned_data.get("ReEnterPassword")
        if(len(Name)<5):
            raise forms.ValidationError("Length of Name is too short.Please provide length of Name greater than 5")
        if(ReEnterPassword!=Password):
            raise forms.ValidationError('Please ReEnter the password correctly')

        if not any(i.isupper() for i in Password):
            raise forms.ValidationError("Please enter 1 upper case letter.")

        if not any(i.islower() for i in Password):
            raise forms.ValidationError("Please enter 1 lower case letter.")

        if(len(Password)<6):
            raise forms.ValidationError("Please provide more than 6 characters")

        if not any(i.isnumeric() for i in Password):
            raise forms.ValidationError("Please enter 1 Numeric Value.")

        # for i in range(len(Password)):
        #     ss = ['$', '@', '#', '%']
        #     count=0
        #     if(Password[i] in ss):
        #         count+=1
        # if(count<2):
        #     raise forms.ValidationError("Please enter 2 Special Characters")

Django_MiniProject_2-master/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,UserChangeForm
from .models import CustomUser

class C_UserCreationForm(UserCreationForm):
    class Meta:
        model=CustomUser
        fields=("username","email")


class C_UserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields =UserChangeForm.Meta.fields

Django_MiniProject_2-master/BLOG_POSTS/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.views.generic import TemplateView
from . import forms
from . import form1
from.models import login
from.models import createblog

# Create your views here.

def home(request):
    return HttpResponse("Hello I am in home")


def create(request):
    if request.method=="POST":
        form=forms.loginform(request.POST)
        if form.is_valid():
            form.save()
            return redirect("success")
    else:
        form=forms.loginform()


    return render(request,'BLOG_POSTS/signup.html',{'form':form})


def success(request):
    return render(request,'BLOG_POSTS/success.html')


def create_blog(request):
    if request.method=="POST":
        form=form1.create_blog(request.POST,request.FILES)
        if form.is_valid():
            # form = createblog.objects.get(id=id)
            form.save()
            return redirect("success")


    else:
        form=form1.create_blog()
    return render(request,'BLOG_POSTS/POST_FORM.html',{'form':form})



def show(request):
    create_blogs=createblog.objects.all()
    return render(request,'BLOG_POSTS/POST_LIST.HTML',{'create_blogs':create_blogs})

def destroy(request,id):
    create_blogs = createblog.objects.get(id=id)
    create_blogs.delete()
    return redirect("show")

def edit(request,id):
    createblogs=createblog.objects.get(id=id)
    return render(request,"BLOG_POSTS/eedit.html",{'createblogs':createblogs})

def update(request,id):
    createblogs=createblog.objects.get(id=id)
    form=form1.create_blog(request.POST,instance=createblogs)
    if form.is_valid():
        form.save()
        return redirect("show")
    return render(request,"BLOG_POSTS/eedit.html",{'createblogs':createblogs})

class homepageview(TemplateView):
    template_name='BLOG_POSTS/firstpage.html'


def test(request):
    return render(request,"BLOG_POSTS/test.html")

Django_MiniProject_2-master/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from .forms import C_UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
class SignupView(CreateView):
    form_class =C_UserCreationForm
    success_url= reverse_lazy("login")
    template_name="signup.html"


# Create your views here.

Django_MiniProject_2-master/templates/BLOG_POSTS/POST_FORM.html
<html lang="en">



<head>
{% load staticfiles %}
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>

</head>

<form method="POST" enctype="multipart/form-data">
    <div class="container">
        <div class="jumbotron">

        <h1><center>Welcome to the Create_blog</center></h1>
        {{form.as_p}}
        {%csrf_token%}

        <input type="submit" class="btn btn-primary" value="Create Blog"/>

        </div>
    </div>

</form>


</html>

Django_MiniProject_2-master/templates/BLOG_POSTS/eedit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Index</title>
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
</head>
<body>
<form method="POST" class="post-form" action="/update/{{createblogs.id}}">
        {% csrf_token %}
    <div class="container">
<br>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <h3>Update Details</h3>
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">Author_Name:</label>
    <div class="col-sm-4">
        <input type="text" name="Author_Name" id="id_Author_Name" required maxlength="20" value="{{createblogs.Author_Name}}"/>
    </div>
  </div>
  <div class="form-group row">
    <label class="col-sm-2 col-form-label">places:</label>
    <div class="col-sm-4">
        <input type="text" name="places" id="id_places" required maxlength="100" value="{{createblogs.places}}" />
    </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-2 col-form-label">date:</label>
    <div class="col-sm-4">
        <input type="date" name="date" id="id_date" required maxlength="254" value="{{createblogs.date}}" />
    </div>
  </div>
        <div class="form-group row">
    <label class="col-sm-2 col-form-label">content_blog:</label>
    <div class="col-sm-4">
        <input type="text" name="content_blog" id="id_content_blog" required maxlength="254" value="{{createblogs.content_blog}}" />
    </div>
  </div>
  </div>
  </div>
    <div class="form-group row">
    <label class="col-sm-1 col-form-label"></label>
    <div class="col-sm-4">
    <button type="submit" class="btn btn-success">Update</button>
    </div>
  </div>
</form>
</body>
</html>

Django_MiniProject_2-master/templates/BLOG_POSTS/firstpage.html
{%load socialaccount%}
{% load static from staticfiles %}
<html>
<head>

    <link href ="{% static 'fpage.css' %}" rel="stylesheet" type="text/css"/>
    <title>Document</title>
</head>


<>
<h1><center> Welcome to Travel Blog</center></h1>


{% if user.is_authenticated %}

<center><h2 style="color:#808000;font-weight: bold;font-size: 39px;font-style:oblique"> Hello  {{user.username}} </h2> </center>
<button class="b1"><a href='/BLOG_POSTS/create_blog'> Redirect to Create blog</a></button>
<br/>
<button class="b2"><a href='/BLOG_POSTS/show'> Redirect to Read blog</a></button>
<br/>
<button class="b3"><a href="{% url 'account_logout' %}">Logout </a></button>


{% else %}
<div class="login-box">

<p><button class="btn1"> <a href ="{%url 'account_signup' %}"> Signup </a></button> </p>

    <p><button class="btn2"> <a href = "{%url 'account_login' %}"> Login </a></button> </p>

    <p><button class="btn3"> <a href = "{% provider_login_url 'google' %}"> Login with Gmail </a> </button></p>

    <p> <button class="btn4"><a href = "{% provider_login_url 'twitter' %}"> Login with Twitter </a></button> </p>

    <p><button class="btn5"> <a href = "{% provider_login_url 'facebook' method='oauth2' %}"> Login with Facebook </a></button> </p>
{%endif%}
</div>
</body>
</html>

Django_MiniProject_2-master/templates/BLOG_POSTS/signup.html
{% load staticfiles %}
<html>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
      integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk"
      crossorigin="anonymous">


<!--    <link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">-->


</head>
<body>



<form method="POST">
    <div class="container">
        <div class="jumbotron">

        <h1><center>Welcome to the Signup Page</center></h1>
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" class="btn btn-primary" value="Register"/>

        </div>
    </div>

</form>

<img src="{% static 'img/a.jpeg' %}"/>
</body>
</html>

Django_MiniProject_2-master/templates/BLOG_POSTS/success.html
<html>

<head>
{% load staticfiles %}
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'success.css' %}"/>

</head>

<body>
    <div class="heading_color">
    <h1><center>You have successfully Registered </center></h1>

    <h1><center> Welcome to Blog Page</center></h1>
    <h3> Select the operations that you want to perform</h3>
    <br>
        </div>
    </br>
    <div class="btn_border">
    <center> <a href='/BLOG_POSTS/create_blog' class="btn btn-primary">Create Blog</a></center>
    <br>
    </br>
    <center> <a href='/BLOG_POSTS/show' class="btn btn-primary">Read Blog</a></center>
    <br>
    </br>
    <center> <a href='/BLOG_POSTS/show' class="btn btn-primary">Delete Blog</a></center>
    <br>
    </br>
    <center> <a href='/BLOG_POSTS/show' class="btn btn-primary">Edit Blog</a></center>
</div>
</body>

</html>

Django_MiniProject_2-master/templates/BLOG_POSTS/test.html
{% load staticfiles %}
<html>
<head>
        <title>Document</title>
     <link href ="{% static 'home.css' %}" rel="stylesheet" type="text/css"/>

</head>
<body>
<h3> hello</h3>

<h1>welcome </h1>
</body>

</html>

Django_MiniProject_2-master/templates/signup.html
<h2>Signup </h2>

<form method ="POST">
    {% csrf_token %}

    {{form.as_p}}

    <button type ="submit ">login </button>
</form>